service: sf-assignment-pow
frameworkVersion: "4"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  memorySize: 256
  logRetentionInDays: 14
  timeout: 300

plugins:
  - serverless-offline

custom:
  esbuild:
    packager: yarn
    minify: false
    sourcemap: false
    target: node22
    watch:
      pattern: ["src/**/*.ts"]

functions:
  graphql:
    handler: src/fn_graphql.handler
    events:
      - httpApi: "*"
